### ISSUE TITLE
Installing opik SDK in editable mode always gives version 0.0.1

### ISSUE THREAD

**Issue by dsblank** [comet-ml/opik#166]
**Describe the bug**

Installing opik SDK in editable mode always gives version 0.0.1

The setup.py script gets the version number from the environment:

https://github.com/comet-ml/opik/blob/main/sdks/python/setup.py#L53

**To Reproduce**

1. git clone git@github.com:comet-ml/opik.git
2. cd opik/sdks/python
3. pip install -e .
4. See message: "Successfully installed opik-0.0.1"

**Expected behavior**

There should be a definitive version number, but it is always 0.0.1.

**Comment by alexkuzmik** [comment]
FYI @liyaka, I agree it's an issue, we need to change it.

Ideally, it would be nice if a separate `version.txt` file would be stored in `sdks/python` folder (so that package installation wouldn't depend on files in the repository root). And during `setup.py` run the content of this file is being read, not the env var with default value 0.0.1
