### ISSUE TITLE
Ragas metric with experiment 

### ISSUE THREAD

**Issue by clementrey-dev** [comet-ml/opik#627]
Hello,

Is it possible to use ragas metric with Opik Experiment ?

Is yes, is there a snippet of code for it ?

Best Regards
Clement

**Comment by jverre** [comment]
Hi @clementrey-dev 
It's been a little while since I've played with Ragas but did you take a look at this cookbook: [https://www.comet.com/docs/opik/cookbook/ragas#evaluating-datasets](https://www.comet.com/docs/opik/cookbook/ragas#evaluating-datasets) 

Let me know how you get on or if you've checked that notebook already. If something isn't clear, I can look at making changes in the docs to clarify how to use Ragas and Opik Experiments

**Comment by jverre** [comment]
Hi @clementrey-dev 
Not sure if it is still relevant but I have updated the docs with some code snippets: https://www.comet.com/docs/opik/tracing/integrations/ragas#2-create-a-scoring-metric-wrapper
